// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const companySlugTaken = `-- name: CompanySlugTaken :one
SELECT EXISTS (SELECT 1 FROM companies WHERE slug = $1)
`

func (q *Queries) CompanySlugTaken(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, companySlugTaken, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAdminAudit = `-- name: CountAdminAudit :one
SELECT count(*) FROM admin_audit WHERE $1::text IS NULL OR target_type = $1::text
`

func (q *Queries) CountAdminAudit(ctx context.Context, targetType *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminAudit, targetType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminCandidates = `-- name: CountAdminCandidates :one
SELECT count(*)
FROM users
WHERE role = 'candidate'
  AND ($1::text IS NULL OR ($1::text = 'suspended') = (suspended_at IS NOT NULL))
  AND normalize_text(first_name || ' ' || last_name || ' ' || email::text) LIKE ALL (
      SELECT '%' || normalize_text(word) || '%' FROM unnest($2::text[]) AS word)
`

type CountAdminCandidatesParams struct {
	Status *string
	Words  []string
}

func (q *Queries) CountAdminCandidates(ctx context.Context, arg CountAdminCandidatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminCandidates, arg.Status, arg.Words)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminCompanies = `-- name: CountAdminCompanies :one
SELECT count(*)
FROM companies
WHERE ($1::text IS NULL OR ($1::text = 'hidden') = (hidden_at IS NOT NULL))
  AND ($2::text IS NULL
       OR ($2::text = 'no-logo' AND logo_key IS NULL AND coalesce(logo_url, '') = '')
       OR ($2::text = 'no-description' AND coalesce(description, '') = '')
       OR ($2::text = 'no-contact'
           AND coalesce(email, '') = '' AND coalesce(phone, '') = '' AND coalesce(website, '') = '')
       OR ($2::text = 'unverified' AND NOT verified))
  AND search_text LIKE ALL (
      SELECT '%' || normalize_text(word) || '%' FROM unnest($3::text[]) AS word)
`

type CountAdminCompaniesParams struct {
	Status  *string
	Quality *string
	Words   []string
}

func (q *Queries) CountAdminCompanies(ctx context.Context, arg CountAdminCompaniesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminCompanies, arg.Status, arg.Quality, arg.Words)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAdminCompany = `-- name: DeleteAdminCompany :one
DELETE FROM companies WHERE slug = $1 RETURNING logo_key
`

// Letters written for the listing go with it (ON DELETE CASCADE); applications must have been checked first.
func (q *Queries) DeleteAdminCompany(ctx context.Context, slug string) (*string, error) {
	row := q.db.QueryRow(ctx, deleteAdminCompany, slug)
	var logo_key *string
	err := row.Scan(&logo_key)
	return logo_key, err
}

const deleteCandidate = `-- name: DeleteCandidate :execrows
DELETE FROM users WHERE id = $1 AND role = 'candidate'
`

// Cascades to sessions, tokens, profile, CV metadata, letters and applications.
func (q *Queries) DeleteCandidate(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCandidate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdminCandidate = `-- name: GetAdminCandidate :one
SELECT u.id, u.email::text AS email, u.first_name, u.last_name, u.email_verified_at, u.suspended_at, u.created_at,
       EXISTS (SELECT 1 FROM candidate_profiles p WHERE p.user_id = u.id
               AND (p.headline <> '' OR cardinality(p.skills) > 0
                    OR EXISTS (SELECT 1 FROM candidate_experiences e WHERE e.user_id = u.id)
                    OR EXISTS (SELECT 1 FROM candidate_educations d WHERE d.user_id = u.id))) AS has_profile,
       EXISTS (SELECT 1 FROM candidate_cvs cv WHERE cv.user_id = u.id) AS has_cv,
       (SELECT count(*) FROM cover_letters l WHERE l.user_id = u.id) AS letters,
       (SELECT count(*) FROM applications a WHERE a.user_id = u.id AND a.status = 'sent') AS applications_sent,
       (SELECT count(*) FROM applications a WHERE a.user_id = u.id AND a.status = 'withdrawn') AS applications_withdrawn
FROM users u
WHERE u.id = $1 AND u.role = 'candidate'
`

type GetAdminCandidateRow struct {
	ID                    uuid.UUID
	Email                 string
	FirstName             string
	LastName              string
	EmailVerifiedAt       *time.Time
	SuspendedAt           *time.Time
	CreatedAt             time.Time
	HasProfile            bool
	HasCv                 bool
	Letters               int64
	ApplicationsSent      int64
	ApplicationsWithdrawn int64
}

// What the back-office may know about a candidate: account status, whether each piece exists, and counts. Never the
// content of the profile, CV, letters or applications. "Has profile" mirrors candidate.Profile.HasContent.
func (q *Queries) GetAdminCandidate(ctx context.Context, id uuid.UUID) (GetAdminCandidateRow, error) {
	row := q.db.QueryRow(ctx, getAdminCandidate, id)
	var i GetAdminCandidateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerifiedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.HasProfile,
		&i.HasCv,
		&i.Letters,
		&i.ApplicationsSent,
		&i.ApplicationsWithdrawn,
	)
	return i, err
}

const getAdminCompany = `-- name: GetAdminCompany :one
SELECT slug, name, sector, company_type, description, website, email, phone, city, address, size, social_links,
       logo_key, verified, hidden_at, curated_at, source, created_at, updated_at,
       (SELECT count(*) FROM applications a WHERE a.company_id = c.id) AS applications,
       (SELECT count(*) FROM cover_letters l WHERE l.company_id = c.id) AS letters
FROM companies c
WHERE slug = $1
`

type GetAdminCompanyRow struct {
	Slug         string
	Name         string
	Sector       string
	CompanyType  *string
	Description  *string
	Website      *string
	Email        *string
	Phone        *string
	City         string
	Address      *string
	Size         *string
	SocialLinks  []byte
	LogoKey      *string
	Verified     bool
	HiddenAt     *time.Time
	CuratedAt    *time.Time
	Source       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Applications int64
	Letters      int64
}

// What refers to the listing is counted: applications block its deletion, letters go with it.
func (q *Queries) GetAdminCompany(ctx context.Context, slug string) (GetAdminCompanyRow, error) {
	row := q.db.QueryRow(ctx, getAdminCompany, slug)
	var i GetAdminCompanyRow
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.Sector,
		&i.CompanyType,
		&i.Description,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.Address,
		&i.Size,
		&i.SocialLinks,
		&i.LogoKey,
		&i.Verified,
		&i.HiddenAt,
		&i.CuratedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Applications,
		&i.Letters,
	)
	return i, err
}

const getAdminStats = `-- name: GetAdminStats :one
SELECT
    (SELECT count(*) FROM users WHERE role = 'candidate') AS candidates,
    (SELECT count(*) FROM users WHERE role = 'candidate' AND created_at >= now() - interval '7 days') AS candidates_last_7_days,
    (SELECT count(*) FROM users WHERE role = 'candidate' AND created_at >= now() - interval '30 days') AS candidates_last_30_days,
    (SELECT count(*) FROM users WHERE role = 'candidate' AND email_verified_at IS NOT NULL) AS verified_emails,
    (SELECT count(*) FROM users WHERE role = 'candidate' AND suspended_at IS NOT NULL) AS suspended_candidates,
    (SELECT count(*) FROM candidate_profiles p
     WHERE p.headline <> '' OR cardinality(p.skills) > 0
        OR EXISTS (SELECT 1 FROM candidate_experiences e WHERE e.user_id = p.user_id)
        OR EXISTS (SELECT 1 FROM candidate_educations d WHERE d.user_id = p.user_id)) AS profiles_with_content,
    (SELECT count(*) FROM candidate_cvs) AS cvs,
    (SELECT count(*) FROM cover_letters) AS letters,
    (SELECT count(*) FROM applications WHERE status = 'sent') AS applications_sent,
    (SELECT count(*) FROM applications WHERE status = 'withdrawn') AS applications_withdrawn,
    (SELECT count(*) FROM companies WHERE hidden_at IS NULL) AS companies_visible,
    (SELECT count(*) FROM companies WHERE hidden_at IS NOT NULL) AS companies_hidden,
    (SELECT count(*) FROM companies WHERE verified) AS companies_verified
`

type GetAdminStatsRow struct {
	Candidates            int64
	CandidatesLast7Days   int64
	CandidatesLast30Days  int64
	VerifiedEmails        int64
	SuspendedCandidates   int64
	ProfilesWithContent   int64
	Cvs                   int64
	Letters               int64
	ApplicationsSent      int64
	ApplicationsWithdrawn int64
	CompaniesVisible      int64
	CompaniesHidden       int64
	CompaniesVerified     int64
}

// Key numbers of the back-office dashboard. "With content" mirrors candidate.Profile.HasContent.
func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.Candidates,
		&i.CandidatesLast7Days,
		&i.CandidatesLast30Days,
		&i.VerifiedEmails,
		&i.SuspendedCandidates,
		&i.ProfilesWithContent,
		&i.Cvs,
		&i.Letters,
		&i.ApplicationsSent,
		&i.ApplicationsWithdrawn,
		&i.CompaniesVisible,
		&i.CompaniesHidden,
		&i.CompaniesVerified,
	)
	return i, err
}

const insertAdminAudit = `-- name: InsertAdminAudit :exec
INSERT INTO admin_audit (admin_id, action, target_type, target_id, changed_fields)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAdminAuditParams struct {
	AdminID       pgtype.UUID
	Action        string
	TargetType    string
	TargetID      string
	ChangedFields []string
}

func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error {
	_, err := q.db.Exec(ctx, insertAdminAudit,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.ChangedFields,
	)
	return err
}

const insertAdminCompany = `-- name: InsertAdminCompany :exec
INSERT INTO companies (slug, name, sector, company_type, description, website, email, phone, city, address, size,
                       social_links, source, curated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 'admin', now())
`

type InsertAdminCompanyParams struct {
	Slug        string
	Name        string
	Sector      string
	CompanyType *string
	Description *string
	Website     *string
	Email       *string
	Phone       *string
	City        string
	Address     *string
	Size        *string
	SocialLinks []byte
}

func (q *Queries) InsertAdminCompany(ctx context.Context, arg InsertAdminCompanyParams) error {
	_, err := q.db.Exec(ctx, insertAdminCompany,
		arg.Slug,
		arg.Name,
		arg.Sector,
		arg.CompanyType,
		arg.Description,
		arg.Website,
		arg.Email,
		arg.Phone,
		arg.City,
		arg.Address,
		arg.Size,
		arg.SocialLinks,
	)
	return err
}

const listAdminAudit = `-- name: ListAdminAudit :many
SELECT a.id, a.action, a.target_type, a.target_id, a.changed_fields, a.created_at,
       coalesce(u.first_name || ' ' || u.last_name, '')::text AS admin_name,
       coalesce(CASE a.target_type
                    WHEN 'company' THEN (SELECT c.name FROM companies c WHERE c.slug = a.target_id)
                    ELSE (SELECT t.first_name || ' ' || t.last_name FROM users t WHERE t.id::text = a.target_id)
                END, '')::text AS target_label
FROM admin_audit a
LEFT JOIN users u ON u.id = a.admin_id
WHERE $1::text IS NULL OR a.target_type = $1::text
ORDER BY a.id DESC
LIMIT $3 OFFSET $2
`

type ListAdminAuditParams struct {
	TargetType *string
	RowOffset  int32
	RowLimit   int32
}

type ListAdminAuditRow struct {
	ID            int64
	Action        string
	TargetType    string
	TargetID      string
	ChangedFields []string
	CreatedAt     time.Time
	AdminName     string
	TargetLabel   string
}

// Back-office activity, newest first, optionally for one kind of target ('company' / 'user'). The admin's name and the
// target's current label are looked up live, empty once the account or listing is gone (nothing personal is kept here).
func (q *Queries) ListAdminAudit(ctx context.Context, arg ListAdminAuditParams) ([]ListAdminAuditRow, error) {
	rows, err := q.db.Query(ctx, listAdminAudit, arg.TargetType, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminAuditRow
	for rows.Next() {
		var i ListAdminAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.ChangedFields,
			&i.CreatedAt,
			&i.AdminName,
			&i.TargetLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidateObjectKeys = `-- name: ListCandidateObjectKeys :many
SELECT cv.object_key FROM candidate_cvs cv WHERE cv.user_id = $1::uuid
UNION ALL
SELECT a.cv_object_key FROM applications a WHERE a.user_id = $1::uuid AND a.cv_object_key IS NOT NULL
`

// Every stored file of a candidate: the current CV and the CV copies of applications.
func (q *Queries) ListCandidateObjectKeys(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listCandidateObjectKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopCompaniesByApplications = `-- name: ListTopCompaniesByApplications :many
SELECT c.slug, c.name, c.city, count(*) AS applications
FROM applications a
JOIN companies c ON c.id = a.company_id
WHERE a.created_at >= now() - interval '30 days'
GROUP BY c.id
ORDER BY applications DESC, c.name
LIMIT 10
`

type ListTopCompaniesByApplicationsRow struct {
	Slug         string
	Name         string
	City         string
	Applications int64
}

// Companies that received the most applications in the last 30 days (sent or since withdrawn).
func (q *Queries) ListTopCompaniesByApplications(ctx context.Context) ([]ListTopCompaniesByApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listTopCompaniesByApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopCompaniesByApplicationsRow
	for rows.Next() {
		var i ListTopCompaniesByApplicationsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.City,
			&i.Applications,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminCompany = `-- name: LockAdminCompany :one
SELECT slug, name, sector, company_type, description, website, email, phone, city, address, size, social_links,
       logo_key, verified, hidden_at, curated_at, source, created_at, updated_at,
       (SELECT count(*) FROM applications a WHERE a.company_id = c.id) AS applications,
       (SELECT count(*) FROM cover_letters l WHERE l.company_id = c.id) AS letters
FROM companies c
WHERE slug = $1
FOR UPDATE
`

type LockAdminCompanyRow struct {
	Slug         string
	Name         string
	Sector       string
	CompanyType  *string
	Description  *string
	Website      *string
	Email        *string
	Phone        *string
	City         string
	Address      *string
	Size         *string
	SocialLinks  []byte
	LogoKey      *string
	Verified     bool
	HiddenAt     *time.Time
	CuratedAt    *time.Time
	Source       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Applications int64
	Letters      int64
}

// Locks the listing while an edit compares it with the new values.
func (q *Queries) LockAdminCompany(ctx context.Context, slug string) (LockAdminCompanyRow, error) {
	row := q.db.QueryRow(ctx, lockAdminCompany, slug)
	var i LockAdminCompanyRow
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.Sector,
		&i.CompanyType,
		&i.Description,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.Address,
		&i.Size,
		&i.SocialLinks,
		&i.LogoKey,
		&i.Verified,
		&i.HiddenAt,
		&i.CuratedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Applications,
		&i.Letters,
	)
	return i, err
}

const lockCandidate = `-- name: LockCandidate :one
SELECT email::text AS email, first_name, suspended_at
FROM users
WHERE id = $1 AND role = 'candidate'
FOR UPDATE
`

type LockCandidateRow struct {
	Email       string
	FirstName   string
	SuspendedAt *time.Time
}

// Serializes changes to one candidate account; admins are out of reach.
func (q *Queries) LockCandidate(ctx context.Context, id uuid.UUID) (LockCandidateRow, error) {
	row := q.db.QueryRow(ctx, lockCandidate, id)
	var i LockCandidateRow
	err := row.Scan(&i.Email, &i.FirstName, &i.SuspendedAt)
	return i, err
}

const lockCompanyLogo = `-- name: LockCompanyLogo :one
SELECT logo_key FROM companies WHERE slug = $1 FOR UPDATE
`

// Locks the listing while its logo is replaced; the previous key is returned so its file can be deleted.
func (q *Queries) LockCompanyLogo(ctx context.Context, slug string) (*string, error) {
	row := q.db.QueryRow(ctx, lockCompanyLogo, slug)
	var logo_key *string
	err := row.Scan(&logo_key)
	return logo_key, err
}

const searchAdminCandidates = `-- name: SearchAdminCandidates :many
SELECT id, email::text AS email, first_name, last_name, email_verified_at, suspended_at, created_at
FROM users
WHERE role = 'candidate'
  AND ($1::text IS NULL OR ($1::text = 'suspended') = (suspended_at IS NOT NULL))
  AND normalize_text(first_name || ' ' || last_name || ' ' || email::text) LIKE ALL (
      SELECT '%' || normalize_text(word) || '%' FROM unnest($2::text[]) AS word)
ORDER BY created_at DESC, id
LIMIT $4 OFFSET $3
`

type SearchAdminCandidatesParams struct {
	Status    *string
	Words     []string
	RowOffset int32
	RowLimit  int32
}

type SearchAdminCandidatesRow struct {
	ID              uuid.UUID
	Email           string
	FirstName       string
	LastName        string
	EmailVerifiedAt *time.Time
	SuspendedAt     *time.Time
	CreatedAt       time.Time
}

// Back-office candidate search, newest first: status 'active' / 'suspended' (NULL = all) and words that must all
// appear in the name or email (LIKE metacharacters already escaped). Keep both filters identical. Admins are never listed.
func (q *Queries) SearchAdminCandidates(ctx context.Context, arg SearchAdminCandidatesParams) ([]SearchAdminCandidatesRow, error) {
	rows, err := q.db.Query(ctx, searchAdminCandidates,
		arg.Status,
		arg.Words,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAdminCandidatesRow
	for rows.Next() {
		var i SearchAdminCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.EmailVerifiedAt,
			&i.SuspendedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAdminCompanies = `-- name: SearchAdminCompanies :many
SELECT slug, name, sector, city, logo_key, verified, hidden_at, curated_at, source, updated_at
FROM companies
WHERE ($1::text IS NULL OR ($1::text = 'hidden') = (hidden_at IS NOT NULL))
  AND ($2::text IS NULL
       OR ($2::text = 'no-logo' AND logo_key IS NULL AND coalesce(logo_url, '') = '')
       OR ($2::text = 'no-description' AND coalesce(description, '') = '')
       OR ($2::text = 'no-contact'
           AND coalesce(email, '') = '' AND coalesce(phone, '') = '' AND coalesce(website, '') = '')
       OR ($2::text = 'unverified' AND NOT verified))
  AND search_text LIKE ALL (
      SELECT '%' || normalize_text(word) || '%' FROM unnest($3::text[]) AS word)
ORDER BY CASE WHEN $4::text = 'updated' THEN updated_at END DESC, name, slug
LIMIT $6 OFFSET $5
`

type SearchAdminCompaniesParams struct {
	Status    *string
	Quality   *string
	Words     []string
	Sort      string
	RowOffset int32
	RowLimit  int32
}

type SearchAdminCompaniesRow struct {
	Slug      string
	Name      string
	Sector    string
	City      string
	LogoKey   *string
	Verified  bool
	HiddenAt  *time.Time
	CuratedAt *time.Time
	Source    string
	UpdatedAt time.Time
}

// Back-office directory search: hidden listings included, filtered by status ('visible' / 'hidden'; NULL = all), by
// a quality gap to fix (see admin.Quality*; NULL = all) and by words that must all appear in search_text (LIKE
// metacharacters already escaped). Keep the filters of both queries identical. Sorted by name, or most recently
// updated first.
func (q *Queries) SearchAdminCompanies(ctx context.Context, arg SearchAdminCompaniesParams) ([]SearchAdminCompaniesRow, error) {
	rows, err := q.db.Query(ctx, searchAdminCompanies,
		arg.Status,
		arg.Quality,
		arg.Words,
		arg.Sort,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAdminCompaniesRow
	for rows.Next() {
		var i SearchAdminCompaniesRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Sector,
			&i.City,
			&i.LogoKey,
			&i.Verified,
			&i.HiddenAt,
			&i.CuratedAt,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sectorExists = `-- name: SectorExists :one
SELECT EXISTS (SELECT 1 FROM sectors WHERE slug = $1)
`

func (q *Queries) SectorExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, sectorExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setCompanyHidden = `-- name: SetCompanyHidden :execrows
UPDATE companies
SET hidden_at = CASE WHEN $1::bool THEN coalesce(hidden_at, now()) END
WHERE slug = $2
`

type SetCompanyHiddenParams struct {
	Hidden bool
	Slug   string
}

// Hiding keeps the first hiding date; showing clears it.
func (q *Queries) SetCompanyHidden(ctx context.Context, arg SetCompanyHiddenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCompanyHidden, arg.Hidden, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCompanyLogo = `-- name: SetCompanyLogo :exec
UPDATE companies SET logo_key = $1, curated_at = now() WHERE slug = $2
`

type SetCompanyLogoParams struct {
	LogoKey *string
	Slug    string
}

// A logo is an edit by the team: the listing becomes curated.
func (q *Queries) SetCompanyLogo(ctx context.Context, arg SetCompanyLogoParams) error {
	_, err := q.db.Exec(ctx, setCompanyLogo, arg.LogoKey, arg.Slug)
	return err
}

const setCompanyVerified = `-- name: SetCompanyVerified :execrows
UPDATE companies SET verified = $1::bool WHERE slug = $2
`

type SetCompanyVerifiedParams struct {
	Verified bool
	Slug     string
}

func (q *Queries) SetCompanyVerified(ctx context.Context, arg SetCompanyVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCompanyVerified, arg.Verified, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserSuspended = `-- name: SetUserSuspended :exec
UPDATE users
SET suspended_at = CASE WHEN $1::bool THEN coalesce(suspended_at, now()) END
WHERE id = $2
`

type SetUserSuspendedParams struct {
	Suspended bool
	ID        uuid.UUID
}

func (q *Queries) SetUserSuspended(ctx context.Context, arg SetUserSuspendedParams) error {
	_, err := q.db.Exec(ctx, setUserSuspended, arg.Suspended, arg.ID)
	return err
}

const updateAdminCompany = `-- name: UpdateAdminCompany :exec
UPDATE companies
SET name = $2, sector = $3, company_type = $4, description = $5, website = $6, email = $7, phone = $8, city = $9,
    address = $10, size = $11, social_links = $12, curated_at = now()
WHERE slug = $1
`

type UpdateAdminCompanyParams struct {
	Slug        string
	Name        string
	Sector      string
	CompanyType *string
	Description *string
	Website     *string
	Email       *string
	Phone       *string
	City        string
	Address     *string
	Size        *string
	SocialLinks []byte
}

func (q *Queries) UpdateAdminCompany(ctx context.Context, arg UpdateAdminCompanyParams) error {
	_, err := q.db.Exec(ctx, updateAdminCompany,
		arg.Slug,
		arg.Name,
		arg.Sector,
		arg.CompanyType,
		arg.Description,
		arg.Website,
		arg.Email,
		arg.Phone,
		arg.City,
		arg.Address,
		arg.Size,
		arg.SocialLinks,
	)
	return err
}
