// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"
)

const getAdminStats = `-- name: GetAdminStats :one
SELECT
    (SELECT count(*) FROM users WHERE role = 'candidate') AS candidates,
    (SELECT count(*) FROM users WHERE role = 'candidate' AND created_at >= now() - interval '7 days') AS candidates_last_7_days,
    (SELECT count(*) FROM users WHERE role = 'candidate' AND created_at >= now() - interval '30 days') AS candidates_last_30_days,
    (SELECT count(*) FROM users WHERE role = 'candidate' AND email_verified_at IS NOT NULL) AS verified_emails,
    (SELECT count(*) FROM users WHERE role = 'candidate' AND suspended_at IS NOT NULL) AS suspended_candidates,
    (SELECT count(*) FROM candidate_profiles p
     WHERE p.headline <> '' OR cardinality(p.skills) > 0
        OR EXISTS (SELECT 1 FROM candidate_experiences e WHERE e.user_id = p.user_id)
        OR EXISTS (SELECT 1 FROM candidate_educations d WHERE d.user_id = p.user_id)) AS profiles_with_content,
    (SELECT count(*) FROM candidate_cvs) AS cvs,
    (SELECT count(*) FROM cover_letters) AS letters,
    (SELECT count(*) FROM applications WHERE status = 'sent') AS applications_sent,
    (SELECT count(*) FROM applications WHERE status = 'withdrawn') AS applications_withdrawn,
    (SELECT count(*) FROM companies WHERE hidden_at IS NULL) AS companies_visible,
    (SELECT count(*) FROM companies WHERE hidden_at IS NOT NULL) AS companies_hidden,
    (SELECT count(*) FROM companies WHERE verified) AS companies_verified
`

type GetAdminStatsRow struct {
	Candidates            int64
	CandidatesLast7Days   int64
	CandidatesLast30Days  int64
	VerifiedEmails        int64
	SuspendedCandidates   int64
	ProfilesWithContent   int64
	Cvs                   int64
	Letters               int64
	ApplicationsSent      int64
	ApplicationsWithdrawn int64
	CompaniesVisible      int64
	CompaniesHidden       int64
	CompaniesVerified     int64
}

// Key numbers of the back-office dashboard. "With content" mirrors candidate.Profile.HasContent.
func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.Candidates,
		&i.CandidatesLast7Days,
		&i.CandidatesLast30Days,
		&i.VerifiedEmails,
		&i.SuspendedCandidates,
		&i.ProfilesWithContent,
		&i.Cvs,
		&i.Letters,
		&i.ApplicationsSent,
		&i.ApplicationsWithdrawn,
		&i.CompaniesVisible,
		&i.CompaniesHidden,
		&i.CompaniesVerified,
	)
	return i, err
}

const listTopCompaniesByApplications = `-- name: ListTopCompaniesByApplications :many
SELECT c.slug, c.name, c.city, count(*) AS applications
FROM applications a
JOIN companies c ON c.id = a.company_id
WHERE a.created_at >= now() - interval '30 days'
GROUP BY c.id
ORDER BY applications DESC, c.name
LIMIT 10
`

type ListTopCompaniesByApplicationsRow struct {
	Slug         string
	Name         string
	City         string
	Applications int64
}

// Companies that received the most applications in the last 30 days (sent or since withdrawn).
func (q *Queries) ListTopCompaniesByApplications(ctx context.Context) ([]ListTopCompaniesByApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listTopCompaniesByApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopCompaniesByApplicationsRow
	for rows.Next() {
		var i ListTopCompaniesByApplicationsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.City,
			&i.Applications,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
