// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countApplicationsSince = `-- name: CountApplicationsSince :one
SELECT count(*) FROM applications WHERE user_id = $1 AND created_at >= $2
`

type CountApplicationsSinceParams struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CountApplicationsSince(ctx context.Context, arg CountApplicationsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getApplication = `-- name: GetApplication :one
SELECT a.id, c.slug, c.name, c.city, a.status, a.created_at, a.withdrawn_at,
       a.first_name, a.last_name, a.email, a.profile, a.letter, a.cv_file_name, a.cv_size_bytes
FROM applications a
JOIN companies c ON c.id = a.company_id
WHERE a.id = $1 AND a.user_id = $2
`

type GetApplicationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetApplicationRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	City        string
	Status      string
	CreatedAt   time.Time
	WithdrawnAt *time.Time
	FirstName   *string
	LastName    *string
	Email       *string
	Profile     []byte
	Letter      *string
	CvFileName  *string
	CvSizeBytes *int32
}

func (q *Queries) GetApplication(ctx context.Context, arg GetApplicationParams) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, arg.ID, arg.UserID)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.Status,
		&i.CreatedAt,
		&i.WithdrawnAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Profile,
		&i.Letter,
		&i.CvFileName,
		&i.CvSizeBytes,
	)
	return i, err
}

const insertApplication = `-- name: InsertApplication :one
INSERT INTO applications (user_id, company_id, first_name, last_name, email, profile, letter, cv_object_key, cv_file_name, cv_size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at
`

type InsertApplicationParams struct {
	UserID      uuid.UUID
	CompanyID   uuid.UUID
	FirstName   *string
	LastName    *string
	Email       *string
	Profile     []byte
	Letter      *string
	CvObjectKey *string
	CvFileName  *string
	CvSizeBytes *int32
}

type InsertApplicationRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) (InsertApplicationRow, error) {
	row := q.db.QueryRow(ctx, insertApplication,
		arg.UserID,
		arg.CompanyID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Profile,
		arg.Letter,
		arg.CvObjectKey,
		arg.CvFileName,
		arg.CvSizeBytes,
	)
	var i InsertApplicationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT a.id, c.slug, c.name, c.city, a.status, a.created_at, a.withdrawn_at
FROM applications a
JOIN companies c ON c.id = a.company_id
WHERE a.user_id = $1
ORDER BY a.created_at DESC
LIMIT 100
`

type ListApplicationsRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	City        string
	Status      string
	CreatedAt   time.Time
	WithdrawnAt *time.Time
}

func (q *Queries) ListApplications(ctx context.Context, userID uuid.UUID) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.City,
			&i.Status,
			&i.CreatedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawApplication = `-- name: WithdrawApplication :one
UPDATE applications AS a
SET status = 'withdrawn', withdrawn_at = now(),
    first_name = NULL, last_name = NULL, email = NULL, profile = NULL, letter = NULL,
    cv_object_key = NULL, cv_file_name = NULL, cv_size_bytes = NULL
FROM applications AS old
WHERE a.id = old.id AND a.id = $1 AND a.user_id = $2 AND a.status = 'sent'
RETURNING old.cv_object_key
`

type WithdrawApplicationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Erases the snapshot and returns the CV copy's key (read before the update), so the caller deletes the file.
// No row when the application is unknown, someone else's, or already withdrawn.
func (q *Queries) WithdrawApplication(ctx context.Context, arg WithdrawApplicationParams) (*string, error) {
	row := q.db.QueryRow(ctx, withdrawApplication, arg.ID, arg.UserID)
	var cv_object_key *string
	err := row.Scan(&cv_object_key)
	return cv_object_key, err
}
