// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :one
UPDATE email_tokens SET used_at = now()
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

type ConsumeEmailTokenParams struct {
	TokenHash []byte
	Purpose   string
}

// Atomic single use: two concurrent clicks on the same link cannot both succeed.
func (q *Queries) ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeEmailToken, arg.TokenHash, arg.Purpose)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_tokens (token_hash, user_id, purpose, expires_at)
VALUES ($1, $2, $3, now() + make_interval(secs => $4::float8))
`

type CreateEmailTokenParams struct {
	TokenHash  []byte
	UserID     uuid.UUID
	Purpose    string
	TtlSeconds float64
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.TtlSeconds,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, now() + make_interval(secs => $3::float8))
RETURNING expires_at
`

type CreateSessionParams struct {
	TokenHash  []byte
	UserID     uuid.UUID
	TtlSeconds float64
}

// Expiry is computed by PostgreSQL, the clock that also checks it.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.TtlSeconds)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, first_name, last_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email::text AS email, role, first_name, last_name, email_verified_at, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         string
	FirstName    string
	LastName     string
}

type CreateUserRow struct {
	ID              uuid.UUID
	Email           string
	Role            string
	FirstName       string
	LastName        string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.FirstName,
		arg.LastName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAdminByEmail = `-- name: DeleteAdminByEmail :execrows
DELETE FROM users WHERE email = $1 AND role = 'admin'
`

// Removes an administrator account (the admin command); candidates are deleted from the back-office instead.
// Their audit entries stay, without an author.
func (q *Queries) DeleteAdminByEmail(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminByEmail, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredEmailTokens = `-- name: DeleteExpiredEmailTokens :execrows
DELETE FROM email_tokens WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredEmailTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email::text AS email, u.role, u.first_name, u.last_name, u.email_verified_at, u.created_at,
       s.expires_at AS session_expires_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now() AND u.suspended_at IS NULL
`

type GetSessionUserRow struct {
	ID               uuid.UUID
	Email            string
	Role             string
	FirstName        string
	LastName         string
	EmailVerifiedAt  *time.Time
	CreatedAt        time.Time
	SessionExpiresAt time.Time
}

// Expired sessions, and those of suspended accounts, never authenticate (even before they are deleted).
func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email::text AS email, role, first_name, last_name, email_verified_at, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID
	Email           string
	Role            string
	FirstName       string
	LastName        string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCredentialsByEmail = `-- name: GetUserCredentialsByEmail :one
SELECT id, email::text AS email, role, first_name, last_name, email_verified_at, created_at, password_hash, suspended_at
FROM users
WHERE email = $1::citext
`

type GetUserCredentialsByEmailRow struct {
	ID              uuid.UUID
	Email           string
	Role            string
	FirstName       string
	LastName        string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	PasswordHash    string
	SuspendedAt     *time.Time
}

func (q *Queries) GetUserCredentialsByEmail(ctx context.Context, email string) (GetUserCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByEmail, email)
	var i GetUserCredentialsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.SuspendedAt,
	)
	return i, err
}

const lockUser = `-- name: LockUser :exec
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// Serializes token issuance per user, so concurrent requests cannot leave two pending links.
func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockUser, id)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = now() WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const retireEmailTokens = `-- name: RetireEmailTokens :exec
UPDATE email_tokens SET used_at = now()
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type RetireEmailTokensParams struct {
	UserID  uuid.UUID
	Purpose string
}

// Retires every pending token of a purpose, so only the latest email link works.
func (q *Queries) RetireEmailTokens(ctx context.Context, arg RetireEmailTokensParams) error {
	_, err := q.db.Exec(ctx, retireEmailTokens, arg.UserID, arg.Purpose)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}
