// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteCV = `-- name: DeleteCV :one
DELETE FROM candidate_cvs WHERE user_id = $1 RETURNING object_key
`

func (q *Queries) DeleteCV(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteCV, userID)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const deleteProfileLists = `-- name: DeleteProfileLists :exec
WITH sectors AS (DELETE FROM candidate_desired_sectors s WHERE s.user_id = $1),
     languages AS (DELETE FROM candidate_languages l WHERE l.user_id = $1),
     experiences AS (DELETE FROM candidate_experiences x WHERE x.user_id = $1)
DELETE FROM candidate_educations e WHERE e.user_id = $1
`

func (q *Queries) DeleteProfileLists(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileLists, userID)
	return err
}

const getCV = `-- name: GetCV :one
SELECT object_key, file_name, size_bytes, uploaded_at FROM candidate_cvs WHERE user_id = $1
`

type GetCVRow struct {
	ObjectKey  string
	FileName   string
	SizeBytes  int32
	UploadedAt time.Time
}

func (q *Queries) GetCV(ctx context.Context, userID uuid.UUID) (GetCVRow, error) {
	row := q.db.QueryRow(ctx, getCV, userID)
	var i GetCVRow
	err := row.Scan(
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.UploadedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT headline, summary, phone, city, skills, updated_at
FROM candidate_profiles
WHERE user_id = $1
`

type GetProfileRow struct {
	Headline  string
	Summary   string
	Phone     string
	City      string
	Skills    []string
	UpdatedAt time.Time
}

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.Headline,
		&i.Summary,
		&i.Phone,
		&i.City,
		&i.Skills,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDesiredSector = `-- name: InsertDesiredSector :exec
INSERT INTO candidate_desired_sectors (user_id, position, sector) VALUES ($1, $2, $3)
`

type InsertDesiredSectorParams struct {
	UserID   uuid.UUID
	Position int16
	Sector   string
}

func (q *Queries) InsertDesiredSector(ctx context.Context, arg InsertDesiredSectorParams) error {
	_, err := q.db.Exec(ctx, insertDesiredSector, arg.UserID, arg.Position, arg.Sector)
	return err
}

const insertEducation = `-- name: InsertEducation :exec
INSERT INTO candidate_educations (user_id, position, degree, school, field, start_month, end_month, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEducationParams struct {
	UserID      uuid.UUID
	Position    int16
	Degree      string
	School      string
	Field       string
	StartMonth  time.Time
	EndMonth    *time.Time
	Description string
}

func (q *Queries) InsertEducation(ctx context.Context, arg InsertEducationParams) error {
	_, err := q.db.Exec(ctx, insertEducation,
		arg.UserID,
		arg.Position,
		arg.Degree,
		arg.School,
		arg.Field,
		arg.StartMonth,
		arg.EndMonth,
		arg.Description,
	)
	return err
}

const insertExperience = `-- name: InsertExperience :exec
INSERT INTO candidate_experiences (user_id, position, title, organization, city, start_month, end_month, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertExperienceParams struct {
	UserID       uuid.UUID
	Position     int16
	Title        string
	Organization string
	City         string
	StartMonth   time.Time
	EndMonth     *time.Time
	Description  string
}

func (q *Queries) InsertExperience(ctx context.Context, arg InsertExperienceParams) error {
	_, err := q.db.Exec(ctx, insertExperience,
		arg.UserID,
		arg.Position,
		arg.Title,
		arg.Organization,
		arg.City,
		arg.StartMonth,
		arg.EndMonth,
		arg.Description,
	)
	return err
}

const insertLanguage = `-- name: InsertLanguage :exec
INSERT INTO candidate_languages (user_id, position, language, level) VALUES ($1, $2, $3, $4)
`

type InsertLanguageParams struct {
	UserID   uuid.UUID
	Position int16
	Language string
	Level    string
}

func (q *Queries) InsertLanguage(ctx context.Context, arg InsertLanguageParams) error {
	_, err := q.db.Exec(ctx, insertLanguage,
		arg.UserID,
		arg.Position,
		arg.Language,
		arg.Level,
	)
	return err
}

const listDesiredSectors = `-- name: ListDesiredSectors :many
SELECT sector FROM candidate_desired_sectors WHERE user_id = $1 ORDER BY position
`

func (q *Queries) ListDesiredSectors(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDesiredSectors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sector string
		if err := rows.Scan(&sector); err != nil {
			return nil, err
		}
		items = append(items, sector)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEducations = `-- name: ListEducations :many
SELECT degree, school, field, start_month, end_month, description
FROM candidate_educations
WHERE user_id = $1
ORDER BY position
`

type ListEducationsRow struct {
	Degree      string
	School      string
	Field       string
	StartMonth  time.Time
	EndMonth    *time.Time
	Description string
}

func (q *Queries) ListEducations(ctx context.Context, userID uuid.UUID) ([]ListEducationsRow, error) {
	rows, err := q.db.Query(ctx, listEducations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEducationsRow
	for rows.Next() {
		var i ListEducationsRow
		if err := rows.Scan(
			&i.Degree,
			&i.School,
			&i.Field,
			&i.StartMonth,
			&i.EndMonth,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExperiences = `-- name: ListExperiences :many
SELECT title, organization, city, start_month, end_month, description
FROM candidate_experiences
WHERE user_id = $1
ORDER BY position
`

type ListExperiencesRow struct {
	Title        string
	Organization string
	City         string
	StartMonth   time.Time
	EndMonth     *time.Time
	Description  string
}

func (q *Queries) ListExperiences(ctx context.Context, userID uuid.UUID) ([]ListExperiencesRow, error) {
	rows, err := q.db.Query(ctx, listExperiences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExperiencesRow
	for rows.Next() {
		var i ListExperiencesRow
		if err := rows.Scan(
			&i.Title,
			&i.Organization,
			&i.City,
			&i.StartMonth,
			&i.EndMonth,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguages = `-- name: ListLanguages :many
SELECT language, level FROM candidate_languages WHERE user_id = $1 ORDER BY position
`

type ListLanguagesRow struct {
	Language string
	Level    string
}

func (q *Queries) ListLanguages(ctx context.Context, userID uuid.UUID) ([]ListLanguagesRow, error) {
	rows, err := q.db.Query(ctx, listLanguages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLanguagesRow
	for rows.Next() {
		var i ListLanguagesRow
		if err := rows.Scan(&i.Language, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCV = `-- name: UpsertCV :one
INSERT INTO candidate_cvs (user_id, object_key, file_name, size_bytes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET object_key = EXCLUDED.object_key, file_name = EXCLUDED.file_name,
    size_bytes = EXCLUDED.size_bytes, uploaded_at = now()
RETURNING uploaded_at
`

type UpsertCVParams struct {
	UserID    uuid.UUID
	ObjectKey string
	FileName  string
	SizeBytes int32
}

func (q *Queries) UpsertCV(ctx context.Context, arg UpsertCVParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, upsertCV,
		arg.UserID,
		arg.ObjectKey,
		arg.FileName,
		arg.SizeBytes,
	)
	var uploaded_at time.Time
	err := row.Scan(&uploaded_at)
	return uploaded_at, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO candidate_profiles (user_id, headline, summary, phone, city, skills)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE
SET headline = EXCLUDED.headline, summary = EXCLUDED.summary, phone = EXCLUDED.phone,
    city = EXCLUDED.city, skills = EXCLUDED.skills
RETURNING updated_at
`

type UpsertProfileParams struct {
	UserID   uuid.UUID
	Headline string
	Summary  string
	Phone    string
	City     string
	Skills   []string
}

// Takes the profile row lock first, so concurrent saves of one profile run one after the other.
func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.Headline,
		arg.Summary,
		arg.Phone,
		arg.City,
		arg.Skills,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
