// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingClaim = `-- name: CancelPendingClaim :execrows
UPDATE company_claims SET status = 'cancelled' WHERE user_id = $1 AND status = 'pending'
`

func (q *Queries) CancelPendingClaim(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingClaim, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const companyHasManager = `-- name: CompanyHasManager :one
SELECT EXISTS (SELECT 1 FROM company_claims WHERE company_id = $1 AND status = 'approved')
`

func (q *Queries) CompanyHasManager(ctx context.Context, companyID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, companyHasManager, companyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAdminClaims = `-- name: CountAdminClaims :one
SELECT count(*) FROM company_claims WHERE status = $1
`

func (q *Queries) CountAdminClaims(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminClaims, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminClaim = `-- name: GetAdminClaim :one
SELECT cl.id, cl.status, cl.job_title, cl.phone, cl.message, cl.decision_reason, cl.created_at, cl.reviewed_at,
       u.id AS user_id, u.first_name, u.last_name, u.email::text AS email, (u.email_verified_at IS NOT NULL)::boolean AS email_verified,
       u.created_at AS user_created_at,
       c.id AS company_id, c.slug, c.name, c.city, c.website, c.email AS company_email, c.verified, c.hidden_at
FROM company_claims cl
JOIN users u ON u.id = cl.user_id
JOIN companies c ON c.id = cl.company_id
WHERE cl.id = $1
`

type GetAdminClaimRow struct {
	ID             uuid.UUID
	Status         string
	JobTitle       string
	Phone          string
	Message        string
	DecisionReason *string
	CreatedAt      time.Time
	ReviewedAt     *time.Time
	UserID         uuid.UUID
	FirstName      string
	LastName       string
	Email          string
	EmailVerified  bool
	UserCreatedAt  time.Time
	CompanyID      uuid.UUID
	Slug           string
	Name           string
	City           string
	Website        *string
	CompanyEmail   *string
	Verified       bool
	HiddenAt       *time.Time
}

func (q *Queries) GetAdminClaim(ctx context.Context, id uuid.UUID) (GetAdminClaimRow, error) {
	row := q.db.QueryRow(ctx, getAdminClaim, id)
	var i GetAdminClaimRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.JobTitle,
		&i.Phone,
		&i.Message,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.UserCreatedAt,
		&i.CompanyID,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.Website,
		&i.CompanyEmail,
		&i.Verified,
		&i.HiddenAt,
	)
	return i, err
}

const getLatestClaim = `-- name: GetLatestClaim :one

SELECT cl.id, cl.status, cl.job_title, cl.phone, cl.message, cl.decision_reason, cl.reviewed_at, cl.created_at,
       c.slug, c.name, c.city, c.logo_key
FROM company_claims cl
JOIN companies c ON c.id = cl.company_id
WHERE cl.user_id = $1
ORDER BY cl.created_at DESC
LIMIT 1
`

type GetLatestClaimRow struct {
	ID             uuid.UUID
	Status         string
	JobTitle       string
	Phone          string
	Message        string
	DecisionReason *string
	ReviewedAt     *time.Time
	CreatedAt      time.Time
	Slug           string
	Name           string
	City           string
	LogoKey        *string
}

// Company accounts asking to manage a listing (see migration 00008).
// The account's most recent request, with the listing it is about.
func (q *Queries) GetLatestClaim(ctx context.Context, userID uuid.UUID) (GetLatestClaimRow, error) {
	row := q.db.QueryRow(ctx, getLatestClaim, userID)
	var i GetLatestClaimRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.JobTitle,
		&i.Phone,
		&i.Message,
		&i.DecisionReason,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.LogoKey,
	)
	return i, err
}

const insertClaim = `-- name: InsertClaim :one
INSERT INTO company_claims (user_id, company_id, job_title, phone, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertClaimParams struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
	JobTitle  string
	Phone     string
	Message   string
}

func (q *Queries) InsertClaim(ctx context.Context, arg InsertClaimParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertClaim,
		arg.UserID,
		arg.CompanyID,
		arg.JobTitle,
		arg.Phone,
		arg.Message,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAdminClaims = `-- name: ListAdminClaims :many

SELECT cl.id, cl.status, cl.job_title, cl.created_at, cl.reviewed_at,
       u.first_name, u.last_name, u.email::text AS email, (u.email_verified_at IS NOT NULL)::boolean AS email_verified,
       c.slug, c.name, c.city
FROM company_claims cl
JOIN users u ON u.id = cl.user_id
JOIN companies c ON c.id = cl.company_id
WHERE cl.status = $1
ORDER BY CASE WHEN cl.status = 'pending' THEN cl.created_at END ASC,
         coalesce(cl.reviewed_at, cl.created_at) DESC
LIMIT $3 OFFSET $2
`

type ListAdminClaimsParams struct {
	Status    string
	RowOffset int32
	RowLimit  int32
}

type ListAdminClaimsRow struct {
	ID            uuid.UUID
	Status        string
	JobTitle      string
	CreatedAt     time.Time
	ReviewedAt    *time.Time
	FirstName     string
	LastName      string
	Email         string
	EmailVerified bool
	Slug          string
	Name          string
	City          string
}

// Back-office review of claims.
// Pending requests oldest first (the queue); reviewed ones most recent first.
func (q *Queries) ListAdminClaims(ctx context.Context, arg ListAdminClaimsParams) ([]ListAdminClaimsRow, error) {
	rows, err := q.db.Query(ctx, listAdminClaims, arg.Status, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminClaimsRow
	for rows.Next() {
		var i ListAdminClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.JobTitle,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Slug,
			&i.Name,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtherClaimsOfCompany = `-- name: ListOtherClaimsOfCompany :many
SELECT cl.id, cl.status, cl.created_at, u.first_name, u.last_name, u.email::text AS email
FROM company_claims cl
JOIN users u ON u.id = cl.user_id
WHERE cl.company_id = $1 AND cl.id <> $2
ORDER BY cl.created_at DESC
LIMIT 20
`

type ListOtherClaimsOfCompanyParams struct {
	CompanyID uuid.UUID
	ID        uuid.UUID
}

type ListOtherClaimsOfCompanyRow struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
	FirstName string
	LastName  string
	Email     string
}

// The other requests on the same listing, for the admin to compare.
func (q *Queries) ListOtherClaimsOfCompany(ctx context.Context, arg ListOtherClaimsOfCompanyParams) ([]ListOtherClaimsOfCompanyRow, error) {
	rows, err := q.db.Query(ctx, listOtherClaimsOfCompany, arg.CompanyID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOtherClaimsOfCompanyRow
	for rows.Next() {
		var i ListOtherClaimsOfCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClaim = `-- name: LockClaim :one
SELECT id, user_id, company_id, status FROM company_claims WHERE id = $1 FOR UPDATE
`

type LockClaimRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CompanyID uuid.UUID
	Status    string
}

func (q *Queries) LockClaim(ctx context.Context, id uuid.UUID) (LockClaimRow, error) {
	row := q.db.QueryRow(ctx, lockClaim, id)
	var i LockClaimRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Status,
	)
	return i, err
}

const markCompanyVerifiedByClaim = `-- name: MarkCompanyVerifiedByClaim :exec
UPDATE companies SET verified = true, curated_at = now() WHERE id = $1
`

func (q *Queries) MarkCompanyVerifiedByClaim(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCompanyVerifiedByClaim, id)
	return err
}

const rejectOtherPendingClaims = `-- name: RejectOtherPendingClaims :many
WITH rejected AS (
    UPDATE company_claims AS pending
    SET status = 'rejected', decision_reason = $1, reviewed_by = $2, reviewed_at = now()
    WHERE pending.company_id = $3 AND pending.id <> $4 AND pending.status = 'pending'
    RETURNING pending.id, pending.user_id
)
SELECT r.id, u.email::text AS email, u.first_name
FROM rejected r
JOIN users u ON u.id = r.user_id
`

type RejectOtherPendingClaimsParams struct {
	DecisionReason *string
	ReviewedBy     pgtype.UUID
	CompanyID      uuid.UUID
	ApprovedID     uuid.UUID
}

type RejectOtherPendingClaimsRow struct {
	ID        uuid.UUID
	Email     string
	FirstName string
}

// Once a listing has its manager, the other pending requests on it are rejected; their authors are told why.
func (q *Queries) RejectOtherPendingClaims(ctx context.Context, arg RejectOtherPendingClaimsParams) ([]RejectOtherPendingClaimsRow, error) {
	rows, err := q.db.Query(ctx, rejectOtherPendingClaims,
		arg.DecisionReason,
		arg.ReviewedBy,
		arg.CompanyID,
		arg.ApprovedID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RejectOtherPendingClaimsRow
	for rows.Next() {
		var i RejectOtherPendingClaimsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.FirstName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClaimReview = `-- name: SetClaimReview :exec
UPDATE company_claims
SET status = $1, decision_reason = $2, reviewed_by = $3, reviewed_at = now()
WHERE id = $4
`

type SetClaimReviewParams struct {
	Status         string
	DecisionReason *string
	ReviewedBy     pgtype.UUID
	ID             uuid.UUID
}

func (q *Queries) SetClaimReview(ctx context.Context, arg SetClaimReviewParams) error {
	_, err := q.db.Exec(ctx, setClaimReview,
		arg.Status,
		arg.DecisionReason,
		arg.ReviewedBy,
		arg.ID,
	)
	return err
}
