// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package dbgen

import (
	"context"
)

const countCompanies = `-- name: CountCompanies :one
SELECT count(*)
FROM companies
WHERE ($1::text IS NULL OR sector = $1)
  AND ($2::text IS NULL OR city_key = normalize_text($2))
  AND search_text LIKE ALL (
      SELECT '%' || normalize_text(word) || '%' FROM unnest($3::text[]) AS word)
`

type CountCompaniesParams struct {
	Sector *string
	City   *string
	Words  []string
}

func (q *Queries) CountCompanies(ctx context.Context, arg CountCompaniesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies, arg.Sector, arg.City, arg.Words)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompanyBySlug = `-- name: GetCompanyBySlug :one
SELECT slug, name, sector, company_type, description, website, email, phone, city, address,
       size, logo_url, social_links, accepts_spontaneous, verified, rating, rating_count
FROM companies
WHERE slug = $1
`

type GetCompanyBySlugRow struct {
	Slug               string
	Name               string
	Sector             string
	CompanyType        *string
	Description        *string
	Website            *string
	Email              *string
	Phone              *string
	City               string
	Address            *string
	Size               *string
	LogoUrl            *string
	SocialLinks        []byte
	AcceptsSpontaneous *bool
	Verified           bool
	Rating             *float64
	RatingCount        int32
}

func (q *Queries) GetCompanyBySlug(ctx context.Context, slug string) (GetCompanyBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCompanyBySlug, slug)
	var i GetCompanyBySlugRow
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.Sector,
		&i.CompanyType,
		&i.Description,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.Address,
		&i.Size,
		&i.LogoUrl,
		&i.SocialLinks,
		&i.AcceptsSpontaneous,
		&i.Verified,
		&i.Rating,
		&i.RatingCount,
	)
	return i, err
}

const listCityCounts = `-- name: ListCityCounts :many
SELECT city, company_count
FROM (
    SELECT DISTINCT ON (city_key)
           city,
           (sum(count(*)) OVER (PARTITION BY city_key))::bigint AS company_count
    FROM companies
    GROUP BY city_key, city
    ORDER BY city_key, count(*) DESC, city
) AS merged
ORDER BY company_count DESC, city
`

type ListCityCountsRow struct {
	City         string
	CompanyCount int64
}

// Spelling variants ("Mbodiene" / "Mbodiène") are merged under their most frequent spelling;
// ties go to the first spelling in French order, like the web front.
func (q *Queries) ListCityCounts(ctx context.Context) ([]ListCityCountsRow, error) {
	rows, err := q.db.Query(ctx, listCityCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCityCountsRow
	for rows.Next() {
		var i ListCityCountsRow
		if err := rows.Scan(&i.City, &i.CompanyCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanySlugs = `-- name: ListCompanySlugs :many
SELECT slug FROM companies ORDER BY slug
`

func (q *Queries) ListCompanySlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCompanySlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectorCounts = `-- name: ListSectorCounts :many
SELECT s.slug, s.label, count(c.id) AS company_count
FROM sectors s
LEFT JOIN companies c ON c.sector = s.slug
GROUP BY s.slug
ORDER BY company_count DESC, s.label
`

type ListSectorCountsRow struct {
	Slug         string
	Label        string
	CompanyCount int64
}

func (q *Queries) ListSectorCounts(ctx context.Context) ([]ListSectorCountsRow, error) {
	rows, err := q.db.Query(ctx, listSectorCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectorCountsRow
	for rows.Next() {
		var i ListSectorCountsRow
		if err := rows.Scan(&i.Slug, &i.Label, &i.CompanyCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCompanies = `-- name: SearchCompanies :many
SELECT slug, name, sector, company_type, description, website, email, phone, city, address,
       size, logo_url, social_links, accepts_spontaneous, verified, rating, rating_count
FROM companies
WHERE ($1::text IS NULL OR sector = $1)
  AND ($2::text IS NULL OR city_key = normalize_text($2))
  AND search_text LIKE ALL (
      SELECT '%' || normalize_text(word) || '%' FROM unnest($3::text[]) AS word)
ORDER BY rating_count DESC, name, slug
LIMIT $5 OFFSET $4
`

type SearchCompaniesParams struct {
	Sector    *string
	City      *string
	Words     []string
	RowOffset int32
	RowLimit  int32
}

type SearchCompaniesRow struct {
	Slug               string
	Name               string
	Sector             string
	CompanyType        *string
	Description        *string
	Website            *string
	Email              *string
	Phone              *string
	City               string
	Address            *string
	Size               *string
	LogoUrl            *string
	SocialLinks        []byte
	AcceptsSpontaneous *bool
	Verified           bool
	Rating             *float64
	RatingCount        int32
}

// Filters shared with CountCompanies (keep them identical): sector slug, city (compared on
// normalize_text) and words that must all appear in search_text, LIKE metacharacters already escaped.
func (q *Queries) SearchCompanies(ctx context.Context, arg SearchCompaniesParams) ([]SearchCompaniesRow, error) {
	rows, err := q.db.Query(ctx, searchCompanies,
		arg.Sector,
		arg.City,
		arg.Words,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCompaniesRow
	for rows.Next() {
		var i SearchCompaniesRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Sector,
			&i.CompanyType,
			&i.Description,
			&i.Website,
			&i.Email,
			&i.Phone,
			&i.City,
			&i.Address,
			&i.Size,
			&i.LogoUrl,
			&i.SocialLinks,
			&i.AcceptsSpontaneous,
			&i.Verified,
			&i.Rating,
			&i.RatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScrapedCompany = `-- name: UpsertScrapedCompany :exec
INSERT INTO companies (
    slug, name, sector, company_type, description, website, email, phone, city, address,
    size, logo_url, social_links, accepts_spontaneous, verified, source, place_id, rating, rating_count, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    sector = EXCLUDED.sector,
    company_type = EXCLUDED.company_type,
    description = EXCLUDED.description,
    website = EXCLUDED.website,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    city = EXCLUDED.city,
    address = EXCLUDED.address,
    size = EXCLUDED.size,
    logo_url = EXCLUDED.logo_url,
    social_links = EXCLUDED.social_links,
    accepts_spontaneous = EXCLUDED.accepts_spontaneous,
    source = EXCLUDED.source,
    place_id = EXCLUDED.place_id,
    rating = EXCLUDED.rating,
    rating_count = EXCLUDED.rating_count,
    notes = EXCLUDED.notes
WHERE NOT companies.verified
`

type UpsertScrapedCompanyParams struct {
	Slug               string
	Name               string
	Sector             string
	CompanyType        *string
	Description        *string
	Website            *string
	Email              *string
	Phone              *string
	City               string
	Address            *string
	Size               *string
	LogoUrl            *string
	SocialLinks        []byte
	AcceptsSpontaneous *bool
	Verified           bool
	Source             string
	PlaceID            *string
	Rating             *float64
	RatingCount        int32
	Notes              *string
}

// Verified (claimed) companies are never overwritten by a re-import of scraped data.
func (q *Queries) UpsertScrapedCompany(ctx context.Context, arg UpsertScrapedCompanyParams) error {
	_, err := q.db.Exec(ctx, upsertScrapedCompany,
		arg.Slug,
		arg.Name,
		arg.Sector,
		arg.CompanyType,
		arg.Description,
		arg.Website,
		arg.Email,
		arg.Phone,
		arg.City,
		arg.Address,
		arg.Size,
		arg.LogoUrl,
		arg.SocialLinks,
		arg.AcceptsSpontaneous,
		arg.Verified,
		arg.Source,
		arg.PlaceID,
		arg.Rating,
		arg.RatingCount,
		arg.Notes,
	)
	return err
}
