// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: letters.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteLetter = `-- name: DeleteLetter :execrows
DELETE FROM cover_letters l
USING companies c
WHERE l.company_id = c.id AND l.user_id = $1 AND c.slug = $2
`

type DeleteLetterParams struct {
	UserID uuid.UUID
	Slug   string
}

func (q *Queries) DeleteLetter(ctx context.Context, arg DeleteLetterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLetter, arg.UserID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompanyIDBySlug = `-- name: GetCompanyIDBySlug :one
SELECT id FROM companies WHERE slug = $1 AND hidden_at IS NULL
`

// Only visible companies take new letters and applications; reading existing ones joins without this filter.
func (q *Queries) GetCompanyIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCompanyIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getLetter = `-- name: GetLetter :one
SELECT c.slug, c.name, c.city, l.content, l.updated_at
FROM cover_letters l
JOIN companies c ON c.id = l.company_id
WHERE l.user_id = $1 AND c.slug = $2
`

type GetLetterParams struct {
	UserID uuid.UUID
	Slug   string
}

type GetLetterRow struct {
	Slug      string
	Name      string
	City      string
	Content   string
	UpdatedAt time.Time
}

func (q *Queries) GetLetter(ctx context.Context, arg GetLetterParams) (GetLetterRow, error) {
	row := q.db.QueryRow(ctx, getLetter, arg.UserID, arg.Slug)
	var i GetLetterRow
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.City,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}

const listLetters = `-- name: ListLetters :many
SELECT c.slug, c.name, c.city, l.content, l.updated_at
FROM cover_letters l
JOIN companies c ON c.id = l.company_id
WHERE l.user_id = $1
ORDER BY l.updated_at DESC
LIMIT 100
`

type ListLettersRow struct {
	Slug      string
	Name      string
	City      string
	Content   string
	UpdatedAt time.Time
}

func (q *Queries) ListLetters(ctx context.Context, userID uuid.UUID) ([]ListLettersRow, error) {
	rows, err := q.db.Query(ctx, listLetters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLettersRow
	for rows.Next() {
		var i ListLettersRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.City,
			&i.Content,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLetter = `-- name: UpsertLetter :one
INSERT INTO cover_letters (user_id, company_id, content)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, company_id) DO UPDATE SET content = EXCLUDED.content
RETURNING updated_at
`

type UpsertLetterParams struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
	Content   string
}

func (q *Queries) UpsertLetter(ctx context.Context, arg UpsertLetterParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, upsertLetter, arg.UserID, arg.CompanyID, arg.Content)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
