// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const companyManagedBySlug = `-- name: CompanyManagedBySlug :one
SELECT EXISTS (
    SELECT 1 FROM company_claims cl JOIN companies c ON c.id = cl.company_id WHERE c.slug = $1 AND cl.status = 'approved'
)
`

func (q *Queries) CompanyManagedBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, companyManagedBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getManagedListing = `-- name: GetManagedListing :one
SELECT slug, name, sector, city, company_type, description, website, email, phone, address, size, social_links,
       logo_key, verified, hidden_at, updated_at
FROM companies
WHERE id = $1
`

type GetManagedListingRow struct {
	Slug        string
	Name        string
	Sector      string
	City        string
	CompanyType *string
	Description *string
	Website     *string
	Email       *string
	Phone       *string
	Address     *string
	Size        *string
	SocialLinks []byte
	LogoKey     *string
	Verified    bool
	HiddenAt    *time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetManagedListing(ctx context.Context, id uuid.UUID) (GetManagedListingRow, error) {
	row := q.db.QueryRow(ctx, getManagedListing, id)
	var i GetManagedListingRow
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.Sector,
		&i.City,
		&i.CompanyType,
		&i.Description,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Size,
		&i.SocialLinks,
		&i.LogoKey,
		&i.Verified,
		&i.HiddenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one

SELECT c.id, c.slug
FROM company_claims cl
JOIN companies c ON c.id = cl.company_id
WHERE cl.user_id = $1 AND cl.status = 'approved'
`

type GetMembershipRow struct {
	ID   uuid.UUID
	Slug string
}

// A listing as its manager (the company account with the approved claim) sees and edits it.
// The listing an account manages, if its claim is approved.
func (q *Queries) GetMembership(ctx context.Context, userID uuid.UUID) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, userID)
	var i GetMembershipRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const insertCompanyActivity = `-- name: InsertCompanyActivity :exec
INSERT INTO company_activity (company_id, user_id, action, changed_fields) VALUES ($1, $2, $3, $4)
`

type InsertCompanyActivityParams struct {
	CompanyID     uuid.UUID
	UserID        pgtype.UUID
	Action        string
	ChangedFields []string
}

func (q *Queries) InsertCompanyActivity(ctx context.Context, arg InsertCompanyActivityParams) error {
	_, err := q.db.Exec(ctx, insertCompanyActivity,
		arg.CompanyID,
		arg.UserID,
		arg.Action,
		arg.ChangedFields,
	)
	return err
}

const lockManagedListing = `-- name: LockManagedListing :one
SELECT slug, name, sector, city, company_type, description, website, email, phone, address, size, social_links,
       logo_key, verified, hidden_at, updated_at
FROM companies
WHERE id = $1
FOR UPDATE
`

type LockManagedListingRow struct {
	Slug        string
	Name        string
	Sector      string
	City        string
	CompanyType *string
	Description *string
	Website     *string
	Email       *string
	Phone       *string
	Address     *string
	Size        *string
	SocialLinks []byte
	LogoKey     *string
	Verified    bool
	HiddenAt    *time.Time
	UpdatedAt   time.Time
}

func (q *Queries) LockManagedListing(ctx context.Context, id uuid.UUID) (LockManagedListingRow, error) {
	row := q.db.QueryRow(ctx, lockManagedListing, id)
	var i LockManagedListingRow
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.Sector,
		&i.City,
		&i.CompanyType,
		&i.Description,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Size,
		&i.SocialLinks,
		&i.LogoKey,
		&i.Verified,
		&i.HiddenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagedListing = `-- name: UpdateManagedListing :exec
UPDATE companies
SET company_type = $2, description = $3, website = $4, email = $5, phone = $6, address = $7, size = $8, social_links = $9
WHERE id = $1
`

type UpdateManagedListingParams struct {
	ID          uuid.UUID
	CompanyType *string
	Description *string
	Website     *string
	Email       *string
	Phone       *string
	Address     *string
	Size        *string
	SocialLinks []byte
}

// The fields a company edits; name, sector and city stay with the team (updated_at is set by a trigger).
func (q *Queries) UpdateManagedListing(ctx context.Context, arg UpdateManagedListingParams) error {
	_, err := q.db.Exec(ctx, updateManagedListing,
		arg.ID,
		arg.CompanyType,
		arg.Description,
		arg.Website,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Size,
		arg.SocialLinks,
	)
	return err
}
