// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type Company struct {
	ID                 uuid.UUID
	Slug               string
	Name               string
	Sector             string
	CompanyType        *string
	Description        *string
	Website            *string
	Email              *string
	Phone              *string
	City               string
	CityKey            string
	Address            *string
	Size               *string
	LogoUrl            *string
	SocialLinks        []byte
	AcceptsSpontaneous *bool
	Verified           bool
	Source             string
	PlaceID            *string
	Rating             *float64
	RatingCount        int32
	Notes              *string
	SearchText         string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type EmailToken struct {
	TokenHash []byte
	UserID    uuid.UUID
	Purpose   string
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Sector struct {
	Slug  string
	Label string
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	Role            string
	FirstName       string
	LastName        string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
