// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID                 pgtype.UUID
	Slug               string
	Name               string
	Sector             string
	CompanyType        *string
	Description        *string
	Website            *string
	Email              *string
	Phone              *string
	City               string
	CityKey            string
	Address            *string
	Size               *string
	LogoUrl            *string
	SocialLinks        []byte
	AcceptsSpontaneous *bool
	Verified           bool
	Source             string
	PlaceID            *string
	Rating             *float64
	RatingCount        int32
	Notes              *string
	SearchText         string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Sector struct {
	Slug  string
	Label string
}
