// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type Application struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CompanyID   uuid.UUID
	Status      string
	FirstName   *string
	LastName    *string
	Email       *string
	Profile     []byte
	Letter      *string
	CvObjectKey *string
	CvFileName  *string
	CvSizeBytes *int32
	CreatedAt   time.Time
	WithdrawnAt *time.Time
}

type CandidateCv struct {
	UserID     uuid.UUID
	ObjectKey  string
	FileName   string
	SizeBytes  int32
	UploadedAt time.Time
}

type CandidateDesiredSector struct {
	UserID   uuid.UUID
	Position int16
	Sector   string
}

type CandidateEducation struct {
	UserID      uuid.UUID
	Position    int16
	Degree      string
	School      string
	Field       string
	StartMonth  time.Time
	EndMonth    *time.Time
	Description string
}

type CandidateExperience struct {
	UserID       uuid.UUID
	Position     int16
	Title        string
	Organization string
	City         string
	StartMonth   time.Time
	EndMonth     *time.Time
	Description  string
}

type CandidateLanguage struct {
	UserID   uuid.UUID
	Position int16
	Language string
	Level    string
}

type CandidateProfile struct {
	UserID    uuid.UUID
	Headline  string
	Summary   string
	Phone     string
	City      string
	Skills    []string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Company struct {
	ID                 uuid.UUID
	Slug               string
	Name               string
	Sector             string
	CompanyType        *string
	Description        *string
	Website            *string
	Email              *string
	Phone              *string
	City               string
	CityKey            string
	Address            *string
	Size               *string
	LogoUrl            *string
	SocialLinks        []byte
	AcceptsSpontaneous *bool
	Verified           bool
	Source             string
	PlaceID            *string
	Rating             *float64
	RatingCount        int32
	Notes              *string
	SearchText         string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type CoverLetter struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type EmailToken struct {
	TokenHash []byte
	UserID    uuid.UUID
	Purpose   string
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Sector struct {
	Slug  string
	Label string
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	Role            string
	FirstName       string
	LastName        string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
